name: AutoResourceChest
main: cn.lanink.autoresourcechest.AutoResourceChest
version: "0.3.0"
api: ["1.0.11"]
load: POSTWORLD
author: "LT_Name"
depend:
  - "KotlinLib"
commands:
  autoresourcechest:
    aliases:
      - "arc"
    usage: "/autoresourcechest help 查看命令帮助"
    description: "AutoResourceChest 管理命令"
    permission: autoresourcechest.admin
permissions:
  autoresourcechest.admin:
    default: op